/**
 * The single source of truth for the client/server contract.
 *
 * This module is imported by both browser and server code, so it must stay
 * free of Node built-ins and side effects.
 */

/** How speaking rights are allocated in a channel. */
export type RoomMode =
  /** One-to-many: the host talks, listeners must be given the mic. */
  | 'broadcast'
  /** Group voice chat: everyone can talk, push-to-talk by default. */
  | 'open';

export type Role = 'host' | 'speaker' | 'listener';

/** Everything the lobby and room header are allowed to know about a channel. */
export interface PublicRoom {
  code: string;
  title: string;
  mode: RoomMode;
  isPrivate: boolean;
  /** Total people connected, including silent listeners. */
  participants: number;
  /** People currently able to publish audio. */
  speakers: number;
  createdAt: number;
}

export interface ChatMessage {
  id: string;
  identity: string;
  name: string;
  text: string;
  ts: number;
}

/* -------------------------------------------------------------------------- */
/* Requests                                                                   */
/* -------------------------------------------------------------------------- */

export interface CreateRoomBody {
  title: string;
  displayName: string;
  mode: RoomMode;
  isPrivate: boolean;
  /** Hide from the public channel list. Joining by code still works. */
  unlisted: boolean;
  password?: string;
  deviceId: string;
}

export interface JoinRoomBody {
  displayName: string;
  password?: string;
  /** Present when the creator returns to their own channel. */
  hostKey?: string;
  deviceId: string;
}

export interface ChatPostBody {
  /**
   * Generated by the sender and reused for the data-channel packet, so late
   * joiners reading history can dedupe against messages they already have.
   */
  id: string;
  identity: string;
  text: string;
}

export type ModerationAction =
  /** Force-mute a speaker's live track. */
  | 'mute'
  /** Remove someone from the channel for this session. */
  | 'kick'
  /** Give a listener the mic (broadcast mode). */
  | 'grant'
  /** Take the mic back. */
  | 'revoke';

export interface ModerateBody {
  hostKey: string;
  action: ModerationAction;
  targetIdentity: string;
}

/* -------------------------------------------------------------------------- */
/* Responses                                                                  */
/* -------------------------------------------------------------------------- */

/** Returned by both POST /api/rooms and POST /api/rooms/[code]/join. */
export interface SessionResponse {
  token: string;
  /** LiveKit WebSocket URL. Sent from the server so the client needs no env. */
  url: string;
  identity: string;
  role: Role;
  /** Only ever returned to the person who created the channel. */
  hostKey?: string;
  room: PublicRoom;
  chat: ChatMessage[];
}

export interface RoomListResponse {
  rooms: PublicRoom[];
}

export interface RoomPeekResponse {
  room: PublicRoom;
  needsPassword: boolean;
}

export interface ChatListResponse {
  messages: ChatMessage[];
}

export interface OkResponse {
  ok: true;
}

/** Every non-2xx response from this API has this shape. */
export interface ApiErrorResponse {
  error: ApiErrorCode;
  message: string;
}

export type ApiErrorCode =
  | 'bad_request'
  | 'not_found'
  | 'bad_password'
  | 'kicked'
  | 'forbidden'
  | 'rate_limited'
  | 'room_full'
  | 'not_configured'
  | 'server_error';

/* -------------------------------------------------------------------------- */
/* Realtime packets (LiveKit data channel)                                    */
/* -------------------------------------------------------------------------- */

export const DATA_TOPIC = 'airwave' as const;

export type WirePacket =
  | { t: 'chat'; id: string; name: string; text: string; ts: number }
  /** A listener asking for the mic, or withdrawing the request. */
  | { t: 'hand'; up: boolean; name: string };

/* -------------------------------------------------------------------------- */
/* Limits — enforced on the server, mirrored in the UI                        */
/* -------------------------------------------------------------------------- */

export const LIMITS = {
  nameMin: 1,
  nameMax: 24,
  titleMax: 40,
  chatMax: 500,
  passwordMax: 64,
  /** Messages retained per channel for people who join late. */
  chatHistory: 120,
} as const;

export const MODE_LABEL: Record<RoomMode, string> = {
  broadcast: 'Broadcast',
  open: 'Open floor',
};

export const MODE_HINT: Record<RoomMode, string> = {
  broadcast: 'You talk, everyone listens. Hand out the mic when you want to.',
  open: 'Everyone can talk. Hold the key to speak.',
};
